name: Deploy to Production

on:
  release:
    types:
      - released

concurrency:
  group: prod
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Production
    uses: ./.github/workflows/deploy.yml
    with:
      env: prod
      lambda-function-name: prod-rdi-mbta-backend
      # the release name
      version-name: ${{ github.ref_name }}
    secrets: inherit
