name: Deploy to Development

on:
  workflow_dispatch:
  push:
    branches: [main, feat/migration_ci_cd] # Temporarily added for testing

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Development
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
      lambda-function-name: dev-rdi-mbta-backend
      # the release name
      version-name: ${{ github.ref_name }}
    secrets: inherit
